### ISSUE TITLE
Failed build for hammerhead

### ISSUE THREAD

**Issue by e2002e** [hexdump0815/roll-your-own-lineageos-microg-for-unsupported-devices#2]
Hi, I've followed the steps of the readme but it fails without more error message  than:

`>> [Mon Aug 21 08:34:06 UTC 2023] Branch:  cm-14.1
>> [Mon Aug 21 08:34:06 UTC 2023] Devices: hammerhead
>> [Mon Aug 21 08:34:06 UTC 2023] (Re)initializing branch repository
>> [Mon Aug 21 08:34:07 UTC 2023] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'
>> [Mon Aug 21 08:34:07 UTC 2023] Syncing branch repository
>> [Mon Aug 21 08:35:28 UTC 2023] Applying the restricted signature spoofing patch (based on android_frameworks_base-N.patch) to frameworks/base
>> [Mon Aug 21 08:35:29 UTC 2023] Setting "UNOFFICIAL" as release type
>> [Mon Aug 21 08:35:29 UTC 2023] Adding OTA URL overlay (for custom URL )
>> [Mon Aug 21 08:35:29 UTC 2023] Adding custom packages (GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension )
>> [Mon Aug 21 08:35:29 UTC 2023] Preparing build environment
>> [Mon Aug 21 08:35:37 UTC 2023] Starting build for hammerhead, cm-14.1 branch
>> [Mon Aug 21 08:35:46 UTC 2023] Failed build for hammerhead
>> [Mon Aug 21 08:35:46 UTC 2023] Finishing build for hammerhead
>> [Mon Aug 21 08:35:46 UTC 2023] Cleaning source dir for device hammerhead`

The command line is the same than yours but I've replaced 'potter' with 'hammerhead'.

**Comment by hexdump0815** [comment]
i assume you used the proper hammerhead manifest - right? it could be that lineageos-14.1 is that old by now that it simply falls apart due to some dependency no longer working ... there should be some log file somewhere giving a bit more of a clue where it fails, but debugging something like this is not easy ...

worst case you could use my latest hammerhead build from 2021 from the releases - afterwards close to no changes were made to 14.1 lineageos anymore, it might even be that the last commits are even in my last image - see: https://review.lineageos.org/q/branch:cm-14.1+(status:merged) - the latest comitted real fix (i.e. no translation fix or readme update) was on august 24 2021 ...

**Comment by e2002e** [comment]
No, I completelly ignored the part about that manifest. Thank you.

Le lun. 21 août 2023 à 22:08, hexdump0815 ***@***.***> a
écrit :

**Comment by hexdump0815** [comment]
please let me know here if you got it working in the end - it would be interesting if it still builds fine this way ...

**Comment by e2002e** [comment]
Hi there.
Looking at the logs, it does seem to build but fails to copy the zip to the output dir.
Issue is that cm14 has python2.7 code that is not compatible with newer versions.
I used "update-alternative" to set python2.7 as the default but am unable to rebuilt the image.
Do you have any clues as how to build from scratch without erasing the build folders in docker ?

I'm going to get your release, It should be advertised on xda as I think a lot of people using nexus 5 want this.

**Comment by hexdump0815** [comment]
thanks for the update ... its a long time ago meanwhile that i did the last build myself, so i do not really remember any tricks to get things working except what i have written down in the readme
